// <auto-generated />
using System;
using HrSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRMApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251204073648_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HrSystem.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("CitizenId")
                        .HasColumnType("longtext")
                        .HasColumnName("citizen_id");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("longtext")
                        .HasColumnName("company_email");

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("contract_end_date");

                    b.Property<DateTime?>("ContractStartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("contract_start_date");

                    b.Property<string>("CurrentAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("current_address");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_of_birth");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("employee_code");

                    b.Property<string>("EmploymentType")
                        .HasColumnType("longtext")
                        .HasColumnName("employment_type");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext")
                        .HasColumnName("gender");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_children");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("manager_id");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("longtext")
                        .HasColumnName("marital_status");

                    b.Property<string>("PersonalEmail")
                        .HasColumnType("longtext")
                        .HasColumnName("personal_email");

                    b.Property<string>("PersonalTaxCode")
                        .HasColumnType("longtext")
                        .HasColumnName("personal_tax_code");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("position_id");

                    b.Property<string>("SocialInsuranceNo")
                        .HasColumnType("longtext")
                        .HasColumnName("social_insurance_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("EmployeeId");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("HrSystem.Models.LeaveRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("longtext")
                        .HasColumnName("attachment_path");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("HalfDay")
                        .HasColumnType("longtext")
                        .HasColumnName("half_day");

                    b.Property<int?>("HandoverEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("handover_employee_id");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("leave_type");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext")
                        .HasColumnName("reason");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.HasKey("RequestId");

                    b.HasIndex("HandoverEmployeeId");

                    b.ToTable("leave_requests");
                });

            modelBuilder.Entity("HrSystem.Models.OvertimeRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<DateTime>("OtDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ot_date");

                    b.Property<string>("OtReason")
                        .HasColumnType("longtext")
                        .HasColumnName("ot_reason");

                    b.Property<string>("ProjectName")
                        .HasColumnType("longtext")
                        .HasColumnName("project_name");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_hours");

                    b.HasKey("RequestId");

                    b.ToTable("overtime_requests");
                });

            modelBuilder.Entity("HrSystem.Models.ProfileUpdateRequest", b =>
                {
                    b.Property<int>("UpdateRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("update_request_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UpdateRequestId"));

                    b.Property<string>("Comment")
                        .HasColumnType("longtext")
                        .HasColumnName("comment");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("RejectReason")
                        .HasColumnType("longtext")
                        .HasColumnName("reject_reason");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("request_date");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("UpdateRequestId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("profile_update_requests");
                });

            modelBuilder.Entity("HrSystem.Models.ProfileUpdateRequestDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detail_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("longtext")
                        .HasColumnName("old_value");

                    b.Property<int>("UpdateRequestId")
                        .HasColumnType("int")
                        .HasColumnName("update_request_id");

                    b.HasKey("DetailId");

                    b.HasIndex("UpdateRequestId");

                    b.ToTable("profile_update_request_details");
                });

            modelBuilder.Entity("HrSystem.Models.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApproverId")
                        .HasColumnType("int")
                        .HasColumnName("approver_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("RejectReason")
                        .HasColumnType("longtext")
                        .HasColumnName("reject_reason");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("request_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("RequestId");

                    b.HasIndex("ApproverId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("requests");
                });

            modelBuilder.Entity("HrSystem.Models.ResignationRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<bool>("HasCompletedHandover")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_completed_handover");

                    b.Property<string>("HrNote")
                        .HasColumnType("longtext")
                        .HasColumnName("hr_note");

                    b.Property<DateTime>("ProposedLastWorkingDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("proposed_last_working_date");

                    b.Property<string>("ResignReason")
                        .HasColumnType("longtext")
                        .HasColumnName("resign_reason");

                    b.HasKey("RequestId");

                    b.ToTable("resignation_requests");
                });

            modelBuilder.Entity("HrSystem.Models.Timesheet", b =>
                {
                    b.Property<int>("TimesheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("timesheet_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TimesheetId"));

                    b.Property<TimeSpan?>("CheckInTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("check_in_time");

                    b.Property<TimeSpan?>("CheckOutTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("check_out_time");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsLate")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_late");

                    b.Property<int?>("LateMinutes")
                        .HasColumnType("int")
                        .HasColumnName("late_minutes");

                    b.Property<decimal?>("TotalHours")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_hours");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("work_date");

                    b.HasKey("TimesheetId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("timesheets");
                });

            modelBuilder.Entity("HrSystem.Models.TimesheetUpdateRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<TimeSpan?>("NewCheckIn")
                        .HasColumnType("time(6)")
                        .HasColumnName("new_check_in");

                    b.Property<TimeSpan?>("NewCheckOut")
                        .HasColumnType("time(6)")
                        .HasColumnName("new_check_out");

                    b.Property<TimeSpan?>("OldCheckIn")
                        .HasColumnType("time(6)")
                        .HasColumnName("old_check_in");

                    b.Property<TimeSpan?>("OldCheckOut")
                        .HasColumnType("time(6)")
                        .HasColumnName("old_check_out");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext")
                        .HasColumnName("reason");

                    b.Property<int>("TimesheetId")
                        .HasColumnType("int")
                        .HasColumnName("timesheet_id");

                    b.HasKey("RequestId");

                    b.HasIndex("TimesheetId");

                    b.ToTable("timesheet_update_requests");
                });

            modelBuilder.Entity("HrSystem.Models.LeaveRequest", b =>
                {
                    b.HasOne("HrSystem.Models.Employee", "HandoverEmployee")
                        .WithMany()
                        .HasForeignKey("HandoverEmployeeId");

                    b.HasOne("HrSystem.Models.Request", "Request")
                        .WithOne("LeaveRequest")
                        .HasForeignKey("HrSystem.Models.LeaveRequest", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HandoverEmployee");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("HrSystem.Models.OvertimeRequest", b =>
                {
                    b.HasOne("HrSystem.Models.Request", "Request")
                        .WithOne("OvertimeRequest")
                        .HasForeignKey("HrSystem.Models.OvertimeRequest", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("HrSystem.Models.ProfileUpdateRequest", b =>
                {
                    b.HasOne("HrSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HrSystem.Models.ProfileUpdateRequestDetail", b =>
                {
                    b.HasOne("HrSystem.Models.ProfileUpdateRequest", "UpdateRequest")
                        .WithMany("Details")
                        .HasForeignKey("UpdateRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpdateRequest");
                });

            modelBuilder.Entity("HrSystem.Models.Request", b =>
                {
                    b.HasOne("HrSystem.Models.Employee", "Approver")
                        .WithMany("ApprovedRequests")
                        .HasForeignKey("ApproverId");

                    b.HasOne("HrSystem.Models.Employee", "Employee")
                        .WithMany("Requests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HrSystem.Models.ResignationRequest", b =>
                {
                    b.HasOne("HrSystem.Models.Request", "Request")
                        .WithOne("ResignationRequest")
                        .HasForeignKey("HrSystem.Models.ResignationRequest", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("HrSystem.Models.Timesheet", b =>
                {
                    b.HasOne("HrSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HrSystem.Models.TimesheetUpdateRequest", b =>
                {
                    b.HasOne("HrSystem.Models.Request", "Request")
                        .WithOne("TimesheetUpdateRequest")
                        .HasForeignKey("HrSystem.Models.TimesheetUpdateRequest", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrSystem.Models.Timesheet", "Timesheet")
                        .WithMany("TimesheetUpdateRequests")
                        .HasForeignKey("TimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Timesheet");
                });

            modelBuilder.Entity("HrSystem.Models.Employee", b =>
                {
                    b.Navigation("ApprovedRequests");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("HrSystem.Models.ProfileUpdateRequest", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("HrSystem.Models.Request", b =>
                {
                    b.Navigation("LeaveRequest");

                    b.Navigation("OvertimeRequest");

                    b.Navigation("ResignationRequest");

                    b.Navigation("TimesheetUpdateRequest");
                });

            modelBuilder.Entity("HrSystem.Models.Timesheet", b =>
                {
                    b.Navigation("TimesheetUpdateRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
